TOPLEVEL_LANG = vhdl
SIM = ghdl

VHDL_SOURCES = ../../../rtl/npu/ternary_pe.vhd
TOPLEVEL = ternary_pe
ARCH = dataflow

MODULE = test_ternary_pe_cocotb

include $(shell cocotb-config --makefiles)/Makefile.sim
